# This is a basic workflow to help you get started with Actions
name: Deploy to Artifactory module2 package
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    container: rocker/verse
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build R package
      run: devtools::build(args = "--no-manual")
      shell: Rscript {0}
    - name: copy R package file
      run: |
        cp /__w/module2/module2_*.tar.gz /__w/module2/th2mageai_0.0.tar.gz
    - name: Publish to Artifactory
      env:
        ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      run: |
        curl -u $ARTIFACTORY_TOKEN  -T "/__w/th2mageai/th2mageai_0.0.tar.gz" -XPOST  "https://thaink2.jfrog.io/artifactory/api/cran/thaink2r-cran-local/sources"
#        chmod +x "${GITHUB_WORKSPACE}/inst/deployer/publish_to_artifactory.sh"
